# Generated by Django 5.1.1 on 2024-09-21 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors_agency', '0002_alter_actor_groups_alter_actor_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='agency',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='actors_agency.agency'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
