# Generated by Django 5.1.1 on 2024-09-21 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors_agency', '0003_character_agency_alter_actor_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='actors_agency.agency'),
        ),
    ]
