# Generated by Django 5.1.1 on 2024-09-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors_agency', '0005_actoragency_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
