# Generated by Django 5.1.1 on 2024-10-31 14:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors_agency', '0006_alter_actor_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='bio',
            field=models.TextField(default='No biography available'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='actoragency',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_agencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='actoragency',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencies', to='actors_agency.agency'),
        ),
        migrations.AlterField(
            model_name='actoragency',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='actors_agency.character'),
        ),
    ]
